---
name: Automation Hub Collection CI
on: 
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "CHANGES/**"
      - "docs/**"
      - "mkdocs.yml"
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  automation_hub_collection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout galaxy_ng
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Checkout the automation hub collection
        uses: actions/checkout@v3
        with:
          repository: ansible/automation_hub_collection
          path: automation_hub_collection

      - name: Build and install the collection
        working-directory: automation_hub_collection
        run: |
          # The ansible.cfg defined in the collection repository might break the test. We want the same variables for installation and running.
          rm -f ansible.cfg
          rm -f galaxy.yml
          mv .github/files/galaxy.yml.j2 .
          ansible all -i localhost, -c local -m template -a "src=galaxy.yml.j2 dest=galaxy.yml" -e collection_namespace=ansible -e collection_name=automation_hub -e collection_version=1.0.0 -e collection_repo=https://github.com/ansible/automation_hub_collection
          ansible-galaxy collection build -vvv
          ansible-galaxy collection install ansible-automation_hub-1.0.0.tar.gz -vvv

      - name: Spin up a standalone galaxy_ng installation
        run: |
          echo "COMPOSE_PROFILE=standalone" > .compose.env
          echo "DEV_SOURCE_PATH=galaxy_ng" >> .compose.env
          make docker/all
          ./compose up -d
          pip3 install --upgrade requests pyyaml
          python3 dev/common/poll.py

      - name: Test the user playbook
        run: ansible-playbook dev/ah_collection_plays/user.yml -vvv

      - name: Test the content playbook
        run: ansible-playbook dev/ah_collection_plays/content.yml -vvv

      - name: Test the repo playbook
        run: ansible-playbook dev/ah_collection_plays/repo.yml -vvv

      - name: Test the ee playbook
        run: ansible-playbook dev/ah_collection_plays/ee.yml -vvv
